Remove rollback from migrations
software-mansion/protostar pull request #1080
Opened 2022-10-26 08:54 UTC by kasperski95

Remove rollback functionality from migrations. This functionality creates more confusion than good.

2022-10-31 10:26 UTC, Arcticae approved these changes

2022-10-31 14:43 UTC, mkaput requested changes
Blocking this PR because it removes a feature without deprecation notice.

Also, I think we can simply not touch migrations code and wait for deployment scripts to be finalized. Then we can remove all migrations code together in the future.

Wdyt?

2022-11-02 09:56 UTC, kasperski95 commented
> Blocking this PR because it removes a feature without deprecation notice.

![Screenshot 2022-11-02 at 10 45 34](https://user-images.githubusercontent.com/9629577/199457468-592c55a4-ad38-4db3-a3db-7bf10175db39.png)

> Also, I think we can simply not touch migrations code and wait for deployment scripts to be finalized. Then we can remove all migrations code together in the future.

There's no point of adding new features to the migrations. However, I wouldn't avoid touching migrations if the change is fast to make, and adds a value to the project even in the shorter perspective.

2022-11-02 11:34 UTC, mkaput approved these changes
You convinced me @kasperski95 😉

2022-11-02 16:14 UTC, merged