Combine Deployment and Deployment CLI pages
software-mansion/protostar pull request #1118
Opened 2022-11-07 13:17 UTC by mkaput

**Stack**:
- #1117
- #1116
- #1115

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2022-11-08 18:22 UTC, Arcticae requested changes
I've presented an alternative division in #1121 which i think is better, but i might be biased because i've done that one :P

2022-11-08 18:22 UTC, Arcticae commented on website/docs/tutorials/08-deploying/README.md
> +
This should not be in `deploying`

2022-11-08 18:22 UTC, Arcticae commented on website/docs/tutorials/08-deploying/README.md
> +network="mainnet"
This also does not belong only in `deploying`

2022-11-09 07:04 UTC, mkaput commented
@Arcticae I like your work more than this. I'll close this PR

2022-11-09 07:04 UTC, closed without merging