Promote OpenZeppelin contract wizard
software-mansion/protostar pull request #1302
Opened 2022-12-22 13:56 UTC by kasperski95

Show link to the OZ contract wizard. It should help newcomers to kick-start the project.

2022-12-22 13:59 UTC, Arcticae requested changes
I don't understand why we need to do this, promoting 3rd party tools is not responsibility of protostar

2022-12-22 15:12 UTC, kasperski95 commented
@Arcticae Implicit responsibility of Protostar is minimizing resources (human time) needed to create and maintain contracts on StarkNet. This link cost us nothing and helps push new projects in a right direction.

2023-01-02 08:22 UTC, MaksymilianDemitraszek requested changes

2023-01-02 08:22 UTC, MaksymilianDemitraszek commented on protostar/commands/init/init_command.py
> +            )
We definiately shouldn't include such stuff in logs. We can consider adding it to the docs but I am not sure about this either

2023-01-09 08:46 UTC, kasperski95 commented
Outvoted

2023-01-09 08:46 UTC, closed without merging