Move hooks setup to corresponding controllers' constructors
software-mansion/protostar pull request #1637
Opened 2023-03-20 19:21 UTC by abulenok

2023-03-21 09:15 UTC, karol-bisztyga approved these changes

2023-03-21 10:23 UTC, Arcticae requested changes
I think this really moves the logic out of controller, but doesn't address the issue itself:
> _"The idea is to move the hooks' assignments to one place where the environment is being set up"_
But really we now have the same thing, just in a different constructor, which i think is even less intuitive (instantiating a `HintLocal` should not have side effects, we should consider `HintLocal` as HOF)

2023-03-21 20:08 UTC, abulenok commented
@Arcticae 
My motivation to put it into HintLocals' constructor was that these hooks are integral to the `ExpectEventsHintLocal` and `ExpectCallHintLocal`. Using these HintLocals without setting `_test_finish_hook` would make little sense.

Do you suggest doing smth like `expect_call_hint_local.setFinishHook(_test_finish_hook)` in `CairoSharedHintLocalFactory`?

Also, could you please elaborate on `consider HintLocal as HOF`?

2023-03-23 12:06 UTC, MaksymilianDemitraszek commented on protostar/cheatable_starknet/callable_hint_locals/expect_events_hint_local.py
> +        self._test_finish_hook.on(self._controller.compare_expected_and_actual_results)
Wouldn't be actually better to define method `finish_hook` in `HintLocal` and presence of the HintLocal in the vm environment would trigger test runner to run this method for each local at the end? We wouldn't have to pass this convoluted `Hook` object? 🤔 
cc @Arcticae

2023-03-23 15:24 UTC, MaksymilianDemitraszek commented on protostar/cheatable_starknet/callable_hint_locals/expect_events_hint_local.py
> +        self._test_finish_hook.on(self._controller.compare_expected_and_actual_results)
Ok then maybe we should just keep those checks in a separate place, and call them from test runner?

2023-03-28 10:08 UTC, abulenok commented
@Arcticae @MaksymilianDemitraszek 
The other option I was thinking about is to create a `def get_finish_hooks() -> Optional[List[Callable]]:` in `CairoSharedHintLocalFactory`, but it feels less "tidy" to me. WDYT?

2023-03-29 13:46 UTC, Arcticae approved these changes
I guess it's better now

2023-04-03 08:33 UTC, MaksymilianDemitraszek approved these changes

2023-04-04 10:33 UTC, merged