Prep for cairo lang 0.11.1
software-mansion/protostar pull request #1902
Opened 2023-05-11 16:24 UTC by abulenok

### Checklist
- [ ] Relevant issue is linked
- [ ] Docs updated/issue for docs created
- [ ] Added relevant tests

2023-05-14 11:05 UTC, abulenok commented
At this moment, tests that are using devnet fail. To make them pass we need a newer version of devnet with cairo-lang updated to 0.11.1

2023-05-15 11:13 UTC, karol-bisztyga reviewed
Ok, I looked at these changes and didn't spot any obvious mistakes. That said, I assume all this is just some refactoring so everything works with a new version, is that correct?

Also a question: why there's no version bump in `pyproject.toml`? I know this is "prepare for" but I'm just curious. Also, we probably don't want to merge this until we bump the version, right?

2023-05-15 15:21 UTC, abulenok commented
@karol-bisztyga Yes, this is mainly a refactoring, the only change of the logic was introduced in `protostar/testing/starkware/contract_based_test_execution_state.py`.

As of `pyproject.toml`, I think when I started to work on this task, `0.11.1a0` was not available on PyPI, so I had to install it with pip. But yeah we can put it into `pyproject.toml` now

> Also, we probably don't want to merge this until we bump the version, right?

Yes, I think we should wait for the official release

2023-05-16 07:42 UTC, karol-bisztyga requested changes
> Yes, I think we should wait for the official release

Ok, I'm going to request changes just to make sure

2023-05-23 22:08 UTC, abulenok commented
The `--profiling` argument is commented out due to an error in import statement https://github.com/software-mansion/protostar/blob/14558019c151121be4ab7f6dd67b12347b3a144c/protostar/profiler/pprof.py#L4

```
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```

`starknet-devnet` requires `web3` 6.0.0, which brings a newer version of `protobuf`. That's why the error occurs

2023-05-24 07:24 UTC, MaksymilianDemitraszek approved these changes
LGTM, Let's just remove everything profiling related before merging

2023-05-24 07:24 UTC, MaksymilianDemitraszek commented on protostar/commands/legacy_commands/test_cairo0/test_cairo0_command.py
> +            # ),
Let's just remove it, we won't be updating it

2023-05-25 06:12 UTC, MaksymilianDemitraszek approved these changes
LGTM

2023-05-26 09:53 UTC, karol-bisztyga approved these changes

2023-05-26 14:08 UTC, merged