Add print rust
software-mansion/protostar pull request #2061
Opened 2023-06-12 09:47 UTC by karol-bisztyga

### Checklist
- [ ] Relevant issue is linked
- [ ] Docs updated/issue for docs created
- [ ] Added relevant tests

2023-06-12 13:07 UTC, cptartur requested changes

2023-06-12 13:07 UTC, cptartur commented on protostar-rust/run_tests.sh
> +popd # cairo-tests
We shouldn't have to use scripts like this. See e2e tests in #2033. This should be rebased.

2023-06-14 12:59 UTC, piotmag769 requested changes
I assume a lot will change in this PR when suggestion from https://github.com/software-mansion/protostar/pull/2059 are applied, requesting changes just to make sure to review it later on

2023-06-14 12:59 UTC, piotmag769 commented on protostar-rust/cairo-tests/declare_test/protostar.toml
We got rid of protostar.toml in the new runner

2023-06-14 12:59 UTC, piotmag769 commented on protostar-rust/cairo-tests/print_test/tests/simple_test.cairo
Can we add tests for printing felts that:
a) do not fit into 31 bytes
b) fit into 31 bytes but are not decodable to ascii

We didn't handle this cases in python runner, currently being fixed in https://github.com/software-mansion/protostar/pull/2070, I think we can do it in a similar way here

2023-06-14 12:59 UTC, piotmag769 commented on pyrightconfig.json
> +  "ignore": ["./starknet_in_rust/", "./blockifier/"]
Why do we ignore `starknet_in_rust` here?

2023-06-15 13:43 UTC, piotmag769 approved these changes

2023-06-16 12:17 UTC, cptartur approved these changes

2023-06-16 12:29 UTC, merged