Display errors in user friendly way
software-mansion/protostar pull request #48
Opened 2022-02-15 17:24 UTC by kasperski95

- added no-color flag

2022-02-16 19:02 UTC, Arcticae requested changes

2022-02-16 19:02 UTC, Arcticae commented on src/utils/retrieve_real_package_name_test.py
> +# Patching doesn't work for some reason
This should be removed?

2022-02-16 19:02 UTC, Arcticae commented on src/utils/standard_log_formatter.py
> +        if level == "DEBUG":
can we do a mapping here?

2022-02-17 10:16 UTC, kasperski95 commented on src/commands/remove/remove_package.py
> +            f"Protostar couldn't find the following package: {package_name}"
Other package managers informs a user that a package couldn't be found. 

- Poetry: `"Package fjsklfjdslk not found"`
- Yarn: `This module isn't specified in a package.json file.`
- Foundry: `error: `pathspec 'lib/bar' did not match any file(s) known to git`
- Bash: `rm ./foo`: No such file or directory

2022-02-17 11:08 UTC, kasperski95 commented on src/commands/install/install_package_from_repo.py
> +            """Git repository must be initialized in order to install packages.
A user may also try to install packages without initializing the project.

2022-02-17 12:22 UTC, Arcticae approved these changes

2022-02-17 12:27 UTC, merged