`deploy` and `declare` docs
software-mansion/protostar pull request #588
Opened 2022-08-05 14:00 UTC by Radinyn

2022-08-08 08:54 UTC, mkaput requested changes

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/03-network_config.md
> +# Network config
```suggestion
# Network configuration
```

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/03-network_config.md
> +---
rename this file to `03-network-config.md`

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/03-network_config.md
> +
please use https://peps.python.org/pep-0589/ to define a type `NetworkConfig` and use it in all snippets in this PR, i.e. `config: NetworkConfig`

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/02-migrations/declare.md
> +[More information about `config`](../network_config).
Please use file paths over URL paths https://docusaurus.io/docs/markdown-features/links

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/02-migrations/deploy_contract.md
> +    *args,
could you please use the `/` syntax to mark that config should be keyword arg?

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/02-migrations/deploy_contract.md
>      self,
rename this file to use `-` instead of `_`

2022-08-08 08:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/02-migrations/declare.md
> +[More information about `config`](../network_config).
```suggestion
The `config` parameter allows passing [network configuration](../03-network-config.md) data. See related documentation for more information.
```

Change this everywhere.

2022-08-08 12:54 UTC, mkaput requested changes

2022-08-08 12:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/03-network-config.md
> +    wait_for_acceptance: bool # Wait for transaction to be accepted on chain
https://peps.python.org/pep-0224/
```suggestion
    wait_for_acceptance: bool
    "Wait for transaction to be accepted on chain."
```

2022-08-08 12:54 UTC, mkaput commented on website/docs/tutorials/06-deploying/03-network-config.md
> +---
```suggestion
```

2022-08-08 13:05 UTC, mkaput requested changes

2022-08-08 13:05 UTC, mkaput commented on website/docs/tutorials/06-deploying/03-network-config.md
> +class CheatcodeNetworkConfig(TypedDict):
you have forgotten to rename in call site snippets

2022-08-08 13:08 UTC, mkaput approved these changes

2022-08-08 15:08 UTC, kasperski95 commented
Blocked by https://github.com/software-mansion/protostar/pull/573

2022-08-09 12:15 UTC, kasperski95 reviewed
There's unnecessary information about network config in testing cheatcodes

2022-08-09 12:15 UTC, kasperski95 commented on website/docs/tutorials/06-deploying/02-migrations/declare.md
> +    config: Optional[CheatcodeNetworkConfig] = None
It would be nice to explain that config must be pass as a keyword argument. The example below could demonstrate that.

2022-08-09 12:15 UTC, kasperski95 commented on website/docs/tutorials/07-testing/02-cheatcodes/deploy.md
> +
`config` parameter is due to the compatibility with the Migration cheatcode

2022-08-09 12:52 UTC, kasperski95 approved these changes
Someone may think that there's a `migration` cheatcode in the testing environment.

2022-08-09 12:52 UTC, kasperski95 commented on website/docs/tutorials/07-testing/02-cheatcodes/declare.md
> +`config` is a keyword only argument kept for compatibility with the [migration cheatcode](../../06-deploying/02-migrations/declare.md). See related documentation for more information.
```suggestion
`config` is a keyword only argument kept for compatibility with the migration [declare cheatcode](../../06-deploying/02-migrations/declare.md). See related documentation for more information.
```

2022-08-09 12:52 UTC, kasperski95 commented on website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
> +`config` is a keyword only argument kept for compatibility with the [migration cheatcode](../../06-deploying/02-migrations/deploy-contract.md). See related documentation for more information.
```suggestion
`config` is a keyword only argument kept for compatibility with the migration [deploy_contract cheatcode](../../06-deploying/02-migrations/deploy-contract.md). See related documentation for more information.
```

2022-08-09 13:13 UTC, merged