Make cheats available in hints
software-mansion/protostar pull request #70
Opened 2022-03-11 19:54 UTC by kasperski95

2022-03-14 13:18 UTC, MaksymilianDemitraszek requested changes
LGTM some questions in comments

2022-03-14 13:20 UTC, kasperski95 commented on src/commands/test/cheatcodes/cheats.py
> +if TYPE_CHECKING:
Importing it normally causes circular dependency error.

2022-03-14 13:23 UTC, kasperski95 commented on src/commands/test/cheatcodes/cheats.py
> +    cheatable_syscall_handler: CheatableSysCallHandler
`TypedDict` it's first what came to my mind. I'll make it use `dataclass`.

2022-03-14 17:22 UTC, kasperski95 commented on src/commands/test/cheatcodes/cheats.py
> +if TYPE_CHECKING:
Code is now refactored. Resolving.

2022-03-17 09:37 UTC, kasperski95 commented
@MaksymilianDemitraszek Can you re-review this PR?

2022-03-17 16:21 UTC, MaksymilianDemitraszek requested changes
LGTM, close to being merge, one minor thing to fix

2022-03-17 16:21 UTC, MaksymilianDemitraszek commented on src/commands/test/runner_with_cheatcodes.py
> +        CairoFunctionRunner.run_from_entrypoint = original_run_from_entrypoint
Probably we have to do the same for `@replace_class` can you please include it here?

2022-03-17 16:26 UTC, kasperski95 commented on src/commands/test/runner_with_cheatcodes.py
> +        CairoFunctionRunner.run_from_entrypoint = original_run_from_entrypoint
Ok, I'll do it

2022-03-18 08:57 UTC, MaksymilianDemitraszek approved these changes

2022-03-18 08:57 UTC, merged