Update `mock_call` docs
software-mansion/protostar pull request #980
Opened 2022-10-12 16:21 UTC by Arcticae

closes #942

2022-10-13 06:43 UTC, mkaput requested changes

2022-10-13 06:43 UTC, mkaput commented on website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
> +- The cheatcode works only for contract's exposed `@view`s. Doesn't work for internal functions, `@external`'s etc.
```suggestion
- This cheatcode works only for contract's exposed `@view`s. It does not work for internal functions, `@external`s etc.
```

2022-10-13 10:29 UTC, MaksymilianDemitraszek requested changes

2022-10-13 10:29 UTC, MaksymilianDemitraszek commented on website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
> +- This cheatcode works only for contract's exposed `@view`s. It does not work for internal functions, `@external`s etc.
I dont think it is a correct information. Please check it.

2022-10-13 11:13 UTC, mkaput approved these changes

2022-10-13 11:44 UTC, kasperski95 approved these changes

2022-10-13 17:03 UTC, MaksymilianDemitraszek requested changes

2022-10-13 17:03 UTC, MaksymilianDemitraszek commented on website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
> +Mocks all calls to a `@view` function with the name `fn_name` of a contract with an address `contract_address` until the returned callable is called.
This is still incorrect

2022-10-13 17:43 UTC, Arcticae commented on website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
> +Mocks all calls to a `@view` function with the name `fn_name` of a contract with an address `contract_address` until the returned callable is called.
damn, you're right

2022-10-13 18:02 UTC, MaksymilianDemitraszek commented on website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
> +Mock works globally, for all contracts, not only the testing contract.
I mean this PR doesn't change anything rn. Cannot we just close it? (I am ok if we want split it into separate lines)

2022-10-14 08:33 UTC, kasperski95 reviewed
Can we highlight somehow this cheatcode doesn't mock internal calls?

2022-10-14 14:57 UTC, Arcticae commented
@kasperski95 
[Highlight that mock call works only for the interface functions](https://github.com/software-mansion/protostar/pull/980/commits/d8602c86e9ad1ac870122497df47ccce876f2936)
is that one good enough?

2022-10-14 16:51 UTC, kasperski95 approved these changes

2022-10-17 10:38 UTC, merged